### PR TITLE
Bug when you try to include text 

### PR DESCRIPTION
**Pull request by markog85**
Hi, I have a problem with the plug and I don't know if is a common bug.
When I copy layer from sketch that include text and paste in AE I receive this error

screen shot 2017-12-13 at 13 16 49
 
Did I do something wrong?

Thanks :)

### CODE REVIEW

**Comment by nicksmithr** [comment]
Also having this issue, @adamplouff referenced in a [note](https://github.com/google/sketch2ae/pull/2/commits/ceea9b1fd2eef5e220df98310e593aef9c282dc5) about Sketch v48 incompatibility, reverting to 47.1 fixes for me. Assuming something in 48 changes the exporting of text layers. Most likely this bug fix in [the update](https://www.sketchapp.com/updates/) —
```
Fixed a rare crash that could occur when converting text to outlines
```

**Comment by nicksmithr** [comment]
Update on this, 48.2 fixes this. Be sure to upgrade Sketch to latest @markog85

**Comment by adamplouff** [comment]
@nicksmithr thanks so much for the update. My laziness finally paid off.

**Comment by markog85** [comment]
@nicksmithr thanks so much for the update!!! :)
Some times this bugs are really annoying and BTW @adamplouff you did an amazing job 👍

**Pull request closed without merging**
